version: '3.8'

services:
  imgazilla-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - imgazilla-redis
      - imgazilla-postgres
      - rembg-service
    networks:
      - imgazilla-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vs0ooog"
      - "traefik.constraint-label=vs0ooog"
      - "traefik.http.routers.imgazilla-app.entryPoints=https"
      - "traefik.http.routers.imgazilla-app.rule=(Host(`figma.imgazilla.app`) && PathPrefix(`/api`))"
      - "traefik.http.middlewares.route-prefix.addprefix.prefix=/api"
      - "traefik.http.routers.imgazilla-app.middlewares=route-prefix@docker"
      - "traefik.http.services.imgazilla-app.loadbalancer.server.port=3000"

  imgazilla-redis:
    image: redis:latest
    restart: always
    container_name: imgazilla-redis
    command: redis-server --requirepass dev
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    networks:
      - imgazilla-net

  imgazilla-postgres:
    image: postgres:latest
    container_name: imgazilla-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DATABASE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DATABASE_NAME} -U $${POSTGRES_DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - imgazilla-net

  rembg-service:
    image: danielgatis/rembg:latest
    container_name: rembg-service
    command: s --host 0.0.0.0 --port 7000 --log_level info
    ports:
      - '7000:7000'
    restart: unless-stopped
    networks:
      - imgazilla-net

networks:
  imgazilla-net:

volumes:
  postgres_data:
  redis_data: