version: '3.8'

services:
  imgazilla-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - imgazilla-redis
      - imgazilla-postgres
    networks:
      - traefik-proxy
      - imgazilla-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.services.imgazilla-app.loadbalancer.server.port=3000
      - traefik.http.routers.api.service=imgazilla-app

  imgazilla-redis:
    image: redis:latest
    restart: always
    container_name: imgazilla-redis
    command: redis-server --requirepass dev
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    networks:
      - imgazilla-net

  imgazilla-postgres:
    image: postgres:latest
    container_name: imgazilla-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DATABASE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DATABASE_NAME} -U $${POSTGRES_DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - imgazilla-net

networks:
  imgazilla-net:
  traefik-proxy:
    external: true

volumes:
  postgres_data:
  redis_data: