version: '3.8'

services:
  imgazilla-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - imgazilla-redis
      - imgazilla-postgres
    networks:
      - imgazilla-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=vs0ooog
      - traefik.constraint-label=vs0ooog
      - traefik.http.routers.imgazilla-app.rule=Host(`figma.imgazilla.app`)
      - traefik.http.routers.imgazilla-app.middlewares=header-check
      - traefik.http.services.imgazilla-app.loadbalancer.server.port=3000

#      - traefik.http.routers.api.service=imgazilla-app

      - traefik.http.middlewares.header-check.headers.customrequestheaders.x-Figma-Signature
      - traefik.http.middlewares.header-check.headers.allowedHostRegexp=^.+$
      - traefik.http.middlewares.header-check.headers.schemes=https,http


#      - traefik.http.routers.block.rule=Host(`figma.imgazilla.app`) && PathPrefix(`/`)
#      - traefik.http.routers.block.service=noop-service
#      - traefik.http.routers.block.priority=1
#      - traefik.http.services.noop-service.loadbalancer.server.url=http://localhost:65535
#      - traefik.http.routers.api.entrypoints=https


  imgazilla-redis:
    image: redis:latest
    restart: always
    container_name: imgazilla-redis
    command: redis-server --requirepass dev
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    networks:
      - imgazilla-net

  imgazilla-postgres:
    image: postgres:latest
    container_name: imgazilla-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DATABASE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DATABASE_NAME} -U $${POSTGRES_DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - imgazilla-net

networks:
  imgazilla-net:

volumes:
  postgres_data:
  redis_data: