version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    networks:
      - nestjs-net

  redis:
    image: redis:latest
    restart: always
    container_name: imgazilla-redis
    command: redis-server --requirepass dev
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - nestjs-net

  postgres:
    image: postgres:latest
    container_name: imgazilla-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_DATABASE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-net

networks:
  nestjs-net:

volumes:
  postgres_data:
  redis_data: